# Generated by Django 6.0.4 on 2026-04-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_recipeingredient'),
        ('recipes', '0003_profile'),
    ]

    operations = [
    ]
